stages:
 - test
 - build


teste_hello-world:
  stage: test
  image: alpine:3.19.1
  script:
    - echo "Hello World"
  only:
   - master


build:
  stage: build
  script:
    - docker build -t course-catalog .
  only:
   - master

