stages:
 - test
 - qualitygate
 - pre-build
 - trivy
 - build

test_unit:
  stage: test
  image: python:3
  script: 
   - pip install -r requirements.txt
   - python test_users.py
  only:
   - master

qualitygate:
  stage: qualitygate
  image: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner -Dsonar.projectKey=course-catalog -Dsonar.sources=. -Dsonar.host.url=http://sonarqube.emerson.cloudns.cl -Dsonar.token=sqp_09a665c92f25dbcc2ef8f5b18eadb0f8b9445f43
  only:
   - master

pre-build:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${DOCKER_HUB_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${DOCKER_HUB_IMAGE}:${CI_JOB_ID}"
      --no-push
  cache:
    key: "${CI_COMMIT_REF_SLUG}-build-cache"
    paths:
      - /docker_cache/


trivy_scan:
  stage: trivy
  image: aquasec/trivy:latest
  script:
    - "trivy image --severity HIGH --format table --output scan.txt ${DOCKER_HUB_IMAGE}:${CI_JOB_ID}"
  artifacts:
    paths:
      - scan.txt  
  only:
   - master

kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${DOCKER_HUB_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${DOCKER_HUB_IMAGE}:${CI_JOB_ID}"
      --destination "${DOCKER_HUB_IMAGE}:latest"
  only:
   - master